# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20180731_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_options',
            field=models.CharField(default='\u826f\u6027,\u6076\u6027', max_length=64),
        ),
    ]
