# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20180801_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
