# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20180805_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='begin_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
