# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_score_begin_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialimage',
            name='image_link',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='materialimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='material_img'),
        ),
    ]
