# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20180806_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialimage',
            name='image_link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
