# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20180807_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=24)),
                ('description', models.CharField(blank=True, default='', max_length=64)),
                ('video_link', models.CharField(default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
