# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_questionstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explain_image_link',
            field=models.CharField(default='', max_length=256),
        ),
    ]
