# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_question_explain_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explain_image_link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
