# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20180822_2058'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='questionstatistics',
            index_together=set([('question_id',)]),
        ),
        migrations.AlterIndexTogether(
            name='score',
            index_together=set([('exam_id', 'user_id')]),
        ),
        migrations.AlterIndexTogether(
            name='user',
            index_together=set([('phone',)]),
        ),
    ]
